apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  labels:
    app: spring-boot-app
spec:
  replicas: 2  # 생성할 Pod 수
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-container
          image: jhjoontacthealth/sample:latest  # Docker 이미지 경로 (프라이빗 레지스트리를 사용 시 레지스트리 URL 포함)
          ports:
            - containerPort: 8080  # Spring Boot 기본 포트

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer  # LoadBalancer 대신 NodePort 사용
