spring:
  threads:
    virtual:
      enabled: true
  application:
    name: sample

logging:
  level:
    org:
      apache:
        hc:
          client5:
            http: DEBUG
            http.wire: DEBUG
