apiVersion: v1
kind: Service
metadata:
  name: nginx-svc2
spec:
  selector:  # 선택해야 할 파드를 지정
    app: nginx  # 파드 Label과 동일
  type: ClusterIP
  ports:
    - name: tcp
      port: 80
      targetPort: 80